const translations = {
	en: {
		title: "Find Your Internship",
		education: "Your Education",
		skills: "Your Skills",
		sector: " Select your sector",
		sectorInterests: "Sector Interests",
		location: "Preferred Location",
		submit: "Get Suggestions",
		descriptionPlaceholder: "Write something here...",
		addYourSkills: "Select your skill",
		descriptionLabel: " Description",
		selectEducation: "Select your education level",
		selectLocation: "Select your location",
		noSkillsAdded: "Please select sectors to view available skills.",
	},
	hi: {
		title: "अपना इंटर्नशिप खोजें",
		education: "आपकी शिक्षा",
		skills: "आपकी स्किल्स",
		sectorInterests: "क्षेत्रीय रुचियां",
		location: "पसंदीदा स्थान",
		submit: "सुझाव प्राप्त करें",
		note: "हम आपके विवरण के आधार पर 3-5 इंटर्नशिप सुझाएंगे।",
		selectEducation: "अपनी शिक्षा स्तर चुनें",
		selectLocation: "अपना स्थान चुनें",
		noSkillsMessage: "उपलब्ध कौशल देखने के लिए क्षेत्र चुनें।",
		descriptionPlaceholder: "यहाँ कुछ लिखें...",
		addYourSkills: "अपना कौशल चुनें",
		descriptionLabel: "विवरण",
		noSkillsAdded: "कृपया उपलब्ध कौशल देखने के लिए सेक्टर चुनें।",
		sector: "क्षेत्र",
	},
	as: {
		title: "আপোনাৰ ইণ্টাৰ্নশ্বিপ বিচাৰক",
		education: "আপোনাৰ শিক্ষা",
		skills: "আপোনাৰ কৌশল",
		sectorInterests: "ক্ষেত্ৰৰ ৰুচি",
		location: "পছন্দৰ স্থান",
		submit: "পৰামৰ্শ লাভ কৰক",
		note: "আপোনাৰ তথ্যৰ ভিত্তিত আমি ৩-৫ ইণ্টাৰ্নশ্বিপ প্ৰস্তাৱ কৰিম।",
		selectEducation: "আপোনাৰ শিক্ষা স্তৰ বাছক",
		selectLocation: "আপোনাৰ স্থান বাছক",
		noSkillsMessage: "উপলব্ধ কৌশল চাবলৈ ক্ষেত্ৰ বাছক।",
		descriptionPlaceholder: "এতিয়া কিবা লিখক...",
		addYourSkills: "আপোনাৰ কৌশল বাছক",
		descriptionLabel: "বিৱৰণ",
		noSkillsAdded: "উপলব্ধ কৌশল চাবলৈ অনুগ্ৰহ কৰি ক্ষেত্ৰ বাছক।",
		sector: "ক্ষেত্ৰ",
	},
	bn: {
		title: "আপনার ইন্টার্নশিপ খুঁজুন",
		education: "আপনার শিক্ষা",
		skills: "আপনার দক্ষতা",
		sectorInterests: "সেক্টরের আগ্রহ",
		location: "পছন্দের অবস্থান",
		submit: "পরামর্শ পান",
		note: "আমরা আপনার বিবরণের ভিত্তিতে ৩-৫ টি ইন্টার্নশিপ পরামর্শ দেব।",
		selectEducation: "আপনার শিক্ষার স্তর নির্বাচন করুন",
		selectLocation: "আপনার অবস্থান নির্বাচন করুন",
		noSkillsMessage: "উপলব্ধ দক্ষতা দেখার জন্য সেক্টর নির্বাচন করুন।",
		descriptionPlaceholder: "এখানে কিছু লিখুন…",
		addYourSkills: "আপনার দক্ষতা নির্বাচন করুন",
		descriptionLabel: "বর্ণনা",
		noSkillsAdded:
			"দয়া করে উপলব্ধ দক্ষতাগুলি দেখার জন্য একটি সেক্টর নির্বাচন করুন।",
		sector: "সেক্টর",
	},
	br: {
		title: "बड़ो इन्टर्नशिप खोजनाय",
		education: "निफ्राय नि लिरथाय",
		skills: "निफ्राय सिफारिस",
		sectorInterests: "थांखि जायनि सावथि",
		location: "गोसो गोथि",
		submit: "सिफारिस लाबो",
		note: "निफ्रायनि डिटेलनि साननाय ३-५ इन्टर्नशिप सिफारिस खालामनाय।",
		selectEducation: "निफ्राय लिरथाय बासाय",
		selectLocation: "निफ्राय गोथि बासाय",
		noSkillsMessage: "उपलब्ध सिफारिसनि नायनो थांखि जाय बासाय।",
		descriptionPlaceholder: "यहां लिखो…",
		addYourSkills: "अपना कौशल चुनो",
		descriptionLabel: "विवरण",
		noSkillsAdded: "कृपया उपलब्ध कौशलों को देखने के लिए एक सेक्टर चुनें।",
		sector: "थांखि",
	},
	doi: {
		title: "अपना इंटर्नशिप लब्बो",
		education: "तंदे शिक्षा",
		skills: "तंदे हुनर",
		sectorInterests: "क्षेत्र रचियाँ",
		location: "पसंदिदा ठाँव",
		submit: "सुझाव लो",
		note: "असी तंदे विवरण आधारते ३-५ इंटर्नशिप सुझावांगे।",
		selectEducation: "अपनी शिक्षा स्तर चुनो",
		selectLocation: "अपना ठाँव चुनो",
		noSkillsMessage: "उपलब्ध हुनर दिखण वास्ते क्षेत्र चुनो।",
		descriptionPlaceholder: "इत्थे कुछ लिखो…",
		addYourSkills: "अपना हुनर चुनो",
		descriptionLabel: "विवरण",
		noSkillsAdded: "कृपया उपलब्ध हुनर देखने के लिए सेक्टर चुनें।",
		sector: "क्षेत्र",
	},
	gu: {
		title: "તમારી ઇન્ટર્નશિપ શોધો",
		education: "તમારું શિક્ષણ",
		skills: "તમારી કુશળતાઓ",
		sectorInterests: "વિભાગીય રસ",
		location: "પસંદ કરેલ સ્થાન",
		submit: "સૂચનો મેળવો",
		note: "અમે તમારી વિગતો પર આધારિત ૩-૫ ઇન્ટર્નશિપ સૂચવશું.",
		selectEducation: "તમારું શિક્ષણ સ્તર પસંદ કરો",
		selectLocation: "તમારું સ્થાન પસંદ કરો",
		noSkillsMessage: "ઉપલબ્ધ કુશળતાઓ જોવા માટે વિભાગ પસંદ કરો.",
		descriptionPlaceholder: "અહીં કંઈક લખો…",
		addYourSkills: "તમારી કુશળતા પસંદ કરો",
		descriptionLabel: "વર્ણન",
		noSkillsAdded: "કૃપા કરીને ઉપલબ્ધ કુશળતાઓ જોવા માટે એક વિભાગ પસંદ કરો.",
		sector: "વિભાગ",
	},
	kn: {
		title: "ನಿಮ್ಮ ಇಂಟರ್ನ್‌ಶಿಪ್ ಹುಡುಕಿ",
		education: "ನಿಮ್ಮ ಶಿಕ್ಷಣ",
		skills: "ನಿಮ್ಮ ಕೌಶಲ್ಯಗಳು",
		sectorInterests: "ಕ್ಷೇತ್ರ ಆಸಕ್ತಿಗಳು",
		location: "ಆಸಕ್ತ ಸ್ಥಳ",
		submit: "ಸಲಹೆಗಳನ್ನು ಪಡೆಯಿರಿ",
		note: "ನಿಮ್ಮ ವಿವರಗಳ ಆಧಾರದಲ್ಲಿ ನಾವು 3-5 ಇಂಟರ್ನ್‌ಶಿಪ್‌ಗಳನ್ನು ಸೂಚಿಸುತ್ತೇವೆ.",
		selectEducation: "ನಿಮ್ಮ ಶಿಕ್ಷಣ ಮಟ್ಟವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
		selectLocation: "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
		noSkillsMessage: "ಲಭ್ಯವಿರುವ ಕೌಶಲ್ಯಗಳನ್ನು ನೋಡಲು ಕ್ಷೇತ್ರಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
		descriptionPlaceholder: "ಇಲ್ಲಿ ಏನಾದರೂ ಬರೆಹ ಮಾಡಿ…",
		addYourSkills: "ನಿಮ್ಮ ಕೌಶಲ್ಯ ಆಯ್ಕೆಮಾಡಿ",
		descriptionLabel: "ವಿವರಣೆ",
		noSkillsAdded: "ದಯವಿಟ್ಟು ಲಭ್ಯವಿರುವ ಕೌಶಲ್ಯಗಳನ್ನು ನೋಡಲು ಕ್ಷೇತ್ರ ಆಯ್ಕೆಮಾಡಿ.",
		sector: "ಕ್ಷೇತ್ರ",
	},
	ks: {
		title: "اپنۍ انٹرن شپ لبھيو",
		education: "تُهند تعلیـم",
		skills: "تُهند صلاحيت",
		sectorInterests: "سیکٹر رُچھیو",
		location: "پسندیدہ جاے",
		submit: "مشورہ لبھیو",
		note: "اسان تُهند تفصيل آسن ۳-۵ انٹرن شپ مشورو كریو۔",
		selectEducation: "اپنئ تعلیـم سطح چونـیو",
		selectLocation: "اپنئ جاے چونـیو",
		noSkillsMessage: "دستياب صلاحيت لبھنۍ کھاتير سکٹر چونـیو۔",
		descriptionPlaceholder: "ایتھ کچھ لکھو…",
		addYourSkills: "اپنی صلاحیت چونـیو",
		descriptionLabel: "تفصیل",
		noSkillsAdded: "براہ کرم دستیاب صلاحیت دیکھنے کے لئے سیکٹر منتخب کریں۔",
		sector: "سیکٹر",
	},
	///
	kok: {
		title: "तुमचें इंटर्नशिप सोदात",
		education: "तुमची शिक्षण",
		skills: "तुमची कौशल्यां",
		sectorInterests: "क्षेत्र रस",
		location: "पसंत केलेलें ठिकाण",
		submit: "सूचना मेळयात",
		note: "आमी तुमच्या तपशीलांनुसार ३-५ इंटर्नशिप सुचयलां.",
		selectEducation: "तुमचें शिक्षण स्तर निवडात",
		selectLocation: "तुमचें ठिकाण निवडात",
		noSkillsMessage: "उपलब्ध कौशल्यां पळोवपाखातीर क्षेत्र निवडात.",
		descriptionPlaceholder: "इथें काही लिहा…",
		addYourSkills: "तुमची कौशल्य निवडा",
		descriptionLabel: "वर्णन",
		noSkillsAdded: "कृपया उपलब्ध कौशल्य पाहण्यासाठी एक क्षेत्र निवडा.",
		sector: "क्षेत्र",
	},
	mai: {
		title: "अपन इंटर्नशिप खोजु",
		education: "अहाँक शिक्षा",
		skills: "अहाँक कौशल",
		sectorInterests: "क्षेत्रीय रुचि",
		location: "पसंद कएल स्थान",
		submit: "सुझाव पाउ",
		note: "अहींक विवरणक आधार पर ३-५ इंटर्नशिप सुझाओल जायत।",
		selectEducation: "अपन शिक्षा स्तर चुनु",
		selectLocation: "अपन स्थान चुनु",
		noSkillsMessage: "उपलब्ध कौशल देखबाक लेल क्षेत्र चुनु।",
		descriptionPlaceholder: "यहाँ कुछ लिखु…",
		addYourSkills: "अपन कौशल चुनु",
		descriptionLabel: "विवरण",
		noSkillsAdded: "कृपया उपलब्ध कौशल देखबाक लेल एक क्षेत्र चुनु।",
		sector: "क्षेत्र",
	},
	ml: {
		title: "നിങ്ങളുടെ ഇന്റേൺഷിപ്പ് കണ്ടെത്തുക",
		education: "നിങ്ങളുടെ വിദ്യാഭ്യാസം",
		skills: "നിങ്ങളുടെ കഴിവുകൾ",
		sectorInterests: "മേഖലാ താൽപര്യങ്ങൾ",
		location: "ആവശ്യമായ സ്ഥലം",
		submit: "പരാമർശങ്ങൾ നേടുക",
		note: "നിങ്ങളുടെ വിവരങ്ങളുടെ അടിസ്ഥാനത്തിൽ 3-5 ഇന്റേൺഷിപ്പുകൾ നിർദേശിക്കും.",
		selectEducation: "നിങ്ങളുടെ വിദ്യാഭ്യാസ നില തിരഞ്ഞെടുക്കുക",
		selectLocation: "നിങ്ങളുടെ സ്ഥലം തിരഞ്ഞെടുക്കുക",
		noSkillsMessage: "ലഭ്യമായ കഴിവുകൾ കാണാൻ മേഖലകൾ തിരഞ്ഞെടുക്കുക.",
		descriptionPlaceholder: "ഇവിടെ ഒന്നുകിൽ എന്തെങ്കിലും എഴുതൂ…",
		addYourSkills: "നിന്റെ കഴിവുകൾ തിരഞ്ഞെടുക്കുക",
		descriptionLabel: "വിവരണം",
		noSkillsAdded: "ദയവായി ലഭ്യമായ കഴിവുകൾ കാണുവാൻ ഒരു മേഖല തിരഞ്ഞെടുക്കുക.",
		sector: "മേഖല",
	},
	mni: {
		title: "ꯑꯃꯥ ꯏꯟꯇꯔꯅꯁꯤꯞ ꯈꯨꯖꯨꯟ",
		education: "ꯑꯃꯥꯢꯅꯥ ꯑꯦꯗꯤꯖꯨꯅ",
		skills: "ꯑꯃꯥꯢꯅꯥ ꯑꯁꯥꯌꯦꯜ",
		sectorInterests: "ꯁꯦꯛꯇꯔ ꯑꯦꯛꯇꯔꯤꯁ꯭ꯇ",
		location: "ꯑꯥꯎꯅꯥ ꯍꯣꯡꯒꯤ ꯂꯃꯥꯛ",
		submit: "ꯃꯅꯤꯡ ꯊꯥꯗꯣ",
		note: "ꯑꯃꯥꯢꯅꯥ ꯑꯦꯗꯤꯖꯨꯅ ꯑꯗꯣꯔꯗꯤꯇꯦ ꯑꯃꯅꯥ ३-५ ꯏꯟꯇꯔꯅꯁꯤꯞ ꯁꯨꯖꯇ ꯇꯧꯕꯤ.",
		selectEducation: "ꯑꯃꯥ ꯑꯦꯗꯤꯖꯨꯅ ꯅꯤꯂ ꯈꯨꯝꯕ",
		selectLocation: "ꯑꯃꯥ ꯂꯃꯥꯛ ꯈꯨꯝꯕ",
		noSkillsMessage: "ꯑꯗꯤꯕ ꯑꯁꯥꯌꯦꯜ ꯁꯨꯖꯇꯝ ꯂꯣꯟꯅꯗꯕ ꯁꯦꯛꯇꯔ ꯈꯨꯝꯕ",
		descriptionPlaceholder: "ꯑꯦꯝ ꯑꯃꯁꯨꯗꯥ ꯈꯨꯖꯨꯟ",
		addYourSkills: "ꯑꯃꯥꯢꯅꯥ ꯑꯁꯥꯌꯦꯜ ꯑꯗꯣꯔꯢꯇ",
		descriptionLabel: "ꯑꯁꯨꯖꯇꯜ",
		noSkillsAdded: "ꯂꯣꯠꯁꯍꯤꯟꯇ ꯑꯗꯣꯔꯢꯇ ꯣꯟꯅꯗꯕ ꯁꯨꯖꯇ ꯁꯦꯛꯇꯔ ꯈꯨꯝꯕ",
		sector: "ꯁꯦꯛꯇꯔ",
	},
	mr: {
		title: "तुमचे इंटर्नशिप शोधा",
		education: "तुमचे शिक्षण",
		skills: "तुमची कौशल्ये",
		sectorInterests: "क्षेत्रीय रुची",
		location: "पसंत केलेले स्थान",
		submit: "सूचना मिळवा",
		note: "आम्ही तुमच्या तपशीलांनुसार ३-५ इंटर्नशिप सुचवू.",
		selectEducation: "तुमचे शिक्षण पातळी निवडा",
		selectLocation: "तुमचे स्थान निवडा",
		noSkillsMessage: "उपलब्ध कौशल्ये पाहण्यासाठी क्षेत्र निवडा.",
		descriptionPlaceholder: "इथे काही लिहा…",
		addYourSkills: "तुमची कौशल्य निवडा",
		descriptionLabel: "वर्णन",
		noSkillsAdded: "कृपया उपलब्ध कौशल्ये पाहण्यासाठी एक क्षेत्र निवडा.",
		sector: "क्षेत्र",
	},
	ne: {
		title: "तपाईँको इन्टर्नशिप खोज्नुहोस्",
		education: "तपाईँको शिक्षा",
		skills: "तपाईँका सीपहरू",
		sectorInterests: "क्षेत्रीय चासो",
		location: "रुचाइएको स्थान",
		submit: "सुझाव प्राप्त गर्नुहोस्",
		note: "हामी तपाईँका विवरणको आधारमा ३-५ इन्टर्नशिप सुझाव दिनेछौं।",
		selectEducation: "तपाईँको शिक्षा स्तर छान्नुहोस्",
		selectLocation: "तपाईँको स्थान छान्नुहोस्",
		noSkillsMessage: "उपलब्ध सीपहरू हेर्न क्षेत्र छान्नुहोस्।",
		descriptionPlaceholder: "यहाँ केही लेख्नुहोस्…",
		addYourSkills: "आफ्नो सीप चयन गर्नुहोस्",
		descriptionLabel: "विवरण",
		noSkillsAdded: "कृपया उपलब्ध सीपहरू हेर्न एक क्षेत्र चयन गर्नुहोस्।",
		sector: "क्षेत्र",
	},
	/////
	or: {
		title: "ଆପଣଙ୍କ ଇଣ୍ଟର୍ନଶିପ୍ ଖୋଜନ୍ତୁ",
		education: "ଆପଣଙ୍କ ଶିକ୍ଷା",
		skills: "ଆପଣଙ୍କ ଦକ୍ଷତା",
		sectorInterests: "କ୍ଷେତ୍ରର ଆଗ୍ରହ",
		location: "ପସନ୍ଦକରା ସ୍ଥାନ",
		submit: "ପରାମର୍ଶ ପାଆନ୍ତୁ",
		note: "ଆମେ ଆପଣଙ୍କ ବିବରଣୀ ଆଧାରରେ 3-5 ଇଣ୍ଟର୍ନଶିପ୍ ସୁପାରିଶ କରିବୁ।",
		selectEducation: "ଆପଣଙ୍କ ଶିକ୍ଷା ସ୍ତର ଚୟନ କରନ୍ତୁ",
		selectLocation: "ଆପଣଙ୍କ ସ୍ଥାନ ଚୟନ କରନ୍ତୁ",
		noSkillsMessage:
			"ଉପଲବ୍ଧ ଦକ୍ଷତାଗୁଡିକୁ ଦେଖିବା ପାଇଁ କ୍ଷେତ୍ରଗୁଡିକୁ ଚୟନ କରନ୍ତୁ।",
		descriptionPlaceholder: "ଏଠାରେ ଏକ କିଛି ଲେଖନ୍ତୁ…",
		addYourSkills: "ଆପଣଙ୍କ ଦକ୍ଷତା ବାଛନ୍ତୁ",
		descriptionLabel: "ବର୍ଣ୍ଣନା",
		noSkillsAdded: "ଦୟାକରି ଉପଲବ୍ଧ ଦକ୍ଷତା ଦେଖିବାକୁ ଏକ କ୍ଷେତ୍ର ଚୟନ କରନ୍ତୁ।",
		sector: "କ୍ଷେତ୍ର",
	},
	pa: {
		title: "ਆਪਣੀ ਇੰਟਰਨਸ਼ਿਪ ਲੱਭੋ",
		education: "ਤੁਹਾਡੀ ਸਿੱਖਿਆ",
		skills: "ਤੁਹਾਡੀਆਂ ਹੁਨਰਾਂ",
		sectorInterests: "ਖੇਤਰ ਦੀਆਂ ਦਿਲਚਸਪੀਆਂ",
		location: "ਪਸੰਦੀਦਾ ਥਾਂ",
		submit: "ਸੁਝਾਅ ਪ੍ਰਾਪਤ ਕਰੋ",
		note: "ਅਸੀਂ ਤੁਹਾਡੇ ਵੇਰਵਿਆਂ ਦੇ ਆਧਾਰ 'ਤੇ 3-5 ਇੰਟਰਨਸ਼ਿਪਾਂ ਦੀ ਸਿਫਾਰਸ਼ ਕਰਾਂਗੇ।",
		selectEducation: "ਆਪਣਾ ਸਿੱਖਿਆ ਪੱਧਰ ਚੁਣੋ",
		selectLocation: "ਆਪਣਾ ਥਾਂ ਚੁਣੋ",
		noSkillsMessage: "ਉਪਲਬਧ ਹੁਨਰਾਂ ਵੇਖਣ ਲਈ ਖੇਤਰ ਚੁਣੋ।",
		descriptionPlaceholder: "ਇੱਥੇ ਕੁਝ ਲਿਖੋ...",
		addYourSkills: "ਆਪਣੇ ਹੁਨਰ ਚੁਣੋ",
		descriptionLabel: "ਵੇਰਵਾ",
		noSkillsAdded: "ਕਿਰਪਾ ਕਰਕੇ ਉਪਲਬਧ ਹੁਨਰ ਵੇਖਣ ਲਈ ਖੇਤਰ ਚੁਣੋ।",
		sector: "ਖੇਤਰ",
	},
	sa: {
		title: "स्वस्य इण्टर्नशिपं अन्वेषय",
		education: "तव शिक्षणम्",
		skills: "तव कौशलानि",
		sectorInterests: "क्षेत्ररुचयः",
		location: "आकाङ्क्षितं स्थानम्",
		submit: "उपदेशान् प्राप्नुहि",
		note: "वयं तव विवरणस्य आधारेण ३-५ इण्टर्नशिपं सुझाविष्यामः।",
		selectEducation: "स्वस्य शिक्षास्तरं वृणु",
		selectLocation: "स्वस्य स्थानं वृणु",
		noSkillsMessage: "उपलब्धकौशलानि द्रष्टुं क्षेत्राणि वृणु।",
		descriptionPlaceholder: "एत्र किमपि लिखतु…",
		addYourSkills: "स्वं कौशलं चयनय",
		descriptionLabel: "विवरणम्",
		noSkillsAdded: "कृपया उपलब्धकौशलानि द्रष्टुं क्षेत्रं चयनय",
		sector: "क्षेत्र",
	},
	sat: {
		title: "ᱟᱢᱟᱱᱟ ᱤᱱᱴᱚᱨᱱᱥᱤᱯ ᱵᱟᱝᱜᱟ",
		education: "ᱟᱢᱟᱱᱟ ᱯᱩᱨᱟᱹᱛᱤ",
		skills: "ᱟᱢᱟᱱᱟ ᱥᱤᱯ",
		sectorInterests: "ᱛᱟᱹᱲᱤ ᱠᱷᱚᱱᱚ",
		location: "ᱚᱱᱚᱞ ᱥᱴᱟᱱ",
		submit: "ᱥᱟᱦᱟᱸ ᱧᱟᱢᱟ",
		note: "ᱟᱢᱟᱱᱟ ᱪᱤᱠᱷᱟᱹᱞ ᱛᱮ 3-5 ᱤᱱᱴᱚᱨᱱᱥᱤᱯ ᱵᱟᱝᱜᱟᱢ।",
		selectEducation: "ᱯᱩᱨᱟᱹᱛᱤ ᱚᱱᱚᱞ",
		selectLocation: "ᱚᱱᱚᱞ ᱥᱴᱟᱱ ᱚᱱᱚᱞ",
		noSkillsMessage: "ᱛᱟᱲᱤ ᱵᱚᱫᱚᱞ ᱥᱤᱯ ᱧᱟᱢᱟᱜ ᱠᱷᱚᱱᱚ ᱚᱱᱚᱞ",
		descriptionPlaceholder: "ᱟᱢ ᱵᱷᱚᱲ ᱚᱪᱚᱜ...",
		addYourSkills: "ᱥᱤᱯ ᱧᱟᱢᱟ",
		descriptionLabel: "ᱚᱪᱚᱜ",
		noSkillsAdded: "ᱛᱟᱹᱲᱤ ᱥᱤᱯ ᱧᱟᱢᱟ ᱵᱚᱫᱚᱞ ᱵᱟᱝ ᱠᱷᱚᱱᱚ",
		sector: "ᱠᱷᱚᱱᱚ",
	},
	sd: {
		title: "پنھنجو انٽرنشپ ڳوليو",
		education: "توھان جي تعليم",
		skills: "توھان جون صلاحيتون",
		sectorInterests: "شعبن ۾ دلچسپي",
		location: "ترجيحي جڳھ",
		submit: "تجويزون حاصل ڪريو",
		note: "اسين توھان جي تفصيل جي بنياد تي 3-5 انٽرنشپ تجويز ڪنداسين.",
		selectEducation: "پنھنجو تعليم سطح چونڊيو",
		selectLocation: "پنھنجو جڳھ چونڊيو",
		noSkillsMessage: "دستياب صلاحيتون ڏسڻ لاءِ شعبا چونڊيو.",
		descriptionPlaceholder: "ھتي ڪجھ لکو...",
		addYourSkills: "پنھنجيون صلاحيتون چونڊيو",
		descriptionLabel: "وضاحت",
		noSkillsAdded: "مھرباني ڪري شعبو چونڊيو جيئن صلاحيتون ڏسي سگھجن.",
		sector: "شعبو",
	},
	ta: {
		title: "உங்கள் இன்டர்ன்ஷிப்பை கண்டுபிடிக்கவும்",
		education: "உங்கள் கல்வி",
		skills: "உங்கள் திறமைகள்",
		sectorInterests: "துறை ஆர்வங்கள்",
		location: "விரும்பிய இடம்",
		submit: "பரிந்துரைகளை பெறவும்",
		note: "உங்கள் விவரங்களை அடிப்படையாகக் கொண்டு 3-5 இன்டர்ன்ஷிப்புகளை பரிந்துரைக்கிறோம்.",
		selectEducation: "உங்கள் கல்வி நிலையை தேர்ந்தெடுக்கவும்",
		selectLocation: "உங்கள் இடத்தை தேர்ந்தெடுக்கவும்",
		noSkillsMessage: "கிடைக்கும் திறமைகளை பார்க்க துறைகளை தேர்ந்தெடுக்கவும்.",
		descriptionPlaceholder: "இங்கே ஏதாவது எழுதுங்கள்...",
		addYourSkills: "உங்கள் திறமையைத் தேர்ந்தெடுக்கவும்",
		descriptionLabel: "விவரம்",
		noSkillsAdded: "திறமைகள் பார்க்க துறையை தேர்ந்தெடுக்கவும்",
		sector: "துறை",
	},
	te: {
		title: "మీ ఇంటర్న్‌షిప్‌ను కనుగొనండి",
		education: "మీ విద్య",
		skills: "మీ స్కిల్స్",
		sectorInterests: "రంగాల ఆసక్తులు",
		location: "ప్రాధాన్యత స్థానం",
		submit: "సూచనలు పొందండి",
		note: "మీ వివరాల ఆధారంగా మేము 3-5 ఇంటర్న్‌షిప్‌లను సూచిస్తాము.",
		selectEducation: "మీ విద్యా స్థాయిని ఎంచుకోండి",
		selectLocation: "మీ స్థానాన్ని ఎంచుకోండి",
		noSkillsMessage: "అందుబాటులో ఉన్న స్కిల్స్ చూడటానికి రంగాలను ఎంచుకోండి.",
		descriptionPlaceholder: "ఇక్కడ ఏదైనా వ్రాయండి...",
		addYourSkills: "మీ నైపుణ్యాన్ని ఎంచుకోండి",
		descriptionLabel: "వివరణ",
		noSkillsAdded: "దయచేసి రంగాన్ని ఎంచుకుని నైపుణ్యాలను చూడండి",
		sector: "రంగం",
	},
	ur: {
		title: "اپنی انٹرنشپ تلاش کریں",
		education: "آپ کی تعلیم",
		skills: "آپ کی مہارتیں",
		sectorInterests: "سیکٹر دلچسپیاں",
		location: "ترجیحی مقام",
		submit: "تجاویز حاصل کریں",
		note: "ہم آپ کی تفصیلات کی بنیاد پر 3 سے 5 انٹرنشپس کی تجویز دیں گے۔",
		selectEducation: "اپنی تعلیمی سطح منتخب کریں",
		selectLocation: "اپنا مقام منتخب کریں",
		noSkillsMessage: "دستیاب مہارتیں دیکھنے کے لیے سیکٹر منتخب کریں۔",
		descriptionPlaceholder: "یہاں کچھ لکھیں...",
		addYourSkills: "اپنی مہارتیں منتخب کریں",
		descriptionLabel: "تفصیل",
		noSkillsAdded: "براہ کرم مہارتیں دیکھنے کے لیے سیکٹر منتخب کریں۔",
		sector: "سیکٹر",
	},
};
export default translations;
