const formStates = [
  { "id": 1, "desc": "Andhra Pradesh" },
  { "id": 2, "desc": "Arunachal Pradesh" },
  { "id": 3, "desc": "Assam" },
  { "id": 4, "desc": "Bihar" },
  { "id": 5, "desc": "Chhattisgarh" },
  { "id": 6, "desc": "Goa" },
  { "id": 7, "desc": "Gujarat" },
  { "id": 8, "desc": "Haryana" },
  { "id": 9, "desc": "Himachal Pradesh" },
  { "id": 10, "desc": "Jharkhand" },
  { "id": 11, "desc": "Karnataka" },
  { "id": 12, "desc": "Kerala" },
  { "id": 13, "desc": "Madhya Pradesh" },
  { "id": 14, "desc": "Maharashtra" },
  { "id": 15, "desc": "Manipur" },
  { "id": 16, "desc": "Meghalaya" },
  { "id": 17, "desc": "Mizoram" },
  { "id": 18, "desc": "Nagaland" },
  { "id": 19, "desc": "Odisha" },
  { "id": 20, "desc": "Punjab" },
  { "id": 21, "desc": "Rajasthan" },
  { "id": 22, "desc": "Sikkim" },
  { "id": 23, "desc": "Tamil Nadu" },
  { "id": 24, "desc": "Telangana" },
  { "id": 25, "desc": "Tripura" },
  { "id": 26, "desc": "Uttar Pradesh" },
  { "id": 27, "desc": "Uttarakhand" },
  { "id": 28, "desc": "West Bengal" },
  { "id": 29, "desc": "Andaman and Nicobar Islands" },
  { "id": 30, "desc": "Chandigarh" },
  { "id": 31, "desc": "Dadra and Nagar Haveli and Daman and Diu" },
  { "id": 32, "desc": "Delhi" },
  { "id": 33, "desc": "Jammu and Kashmir" },
  { "id": 34, "desc": "Ladakh" },
  { "id": 35, "desc": "Lakshadweep" },
  { "id": 36, "desc": "Puducherry" }
];

export default formStates;
